// Question banks for all three games.

// Would You Rather — both players pick one of two options, revealed together.
const WYR = [
  ["Travel the world together for a year", "Build your dream home together"],
  ["Always know how your partner feels", "Have them always know how you feel"],
  ["Cozy movie night in", "Fancy night out"],
  ["Beach honeymoon", "Mountain cabin honeymoon"],
  ["Always share one dessert", "Always get your own dessert"],
  ["Relive your first date", "Peek 10 years into your future"],
  ["Take a couples cooking class", "Take a couples dance class"],
  ["Never argue again", "Argue sometimes but always make up sweetly"],
  ["Get matching tattoos", "Wear matching outfits for a year"],
  ["Breakfast in bed every weekend", "A surprise date once a month"],
  ["Road trip with zero plan", "Perfectly planned vacation"],
  ["Double date every week", "Never double date again"],
  ["Sing a karaoke duet in public", "Slow dance in public"],
  ["Your partner picks your outfits for a month", "You pick theirs for a month"],
  ["Live in a big city together", "Live in a tiny town together"],
  ["Adopt five dogs", "Adopt five cats"],
  ["Only text each other all day", "Only call each other"],
  ["Win the lottery but keep it secret", "Small raise you can celebrate loudly"],
  ["Stargazing picnic", "Sunrise hike"],
  ["Swap phones for a day", "Swap chores for a month"],
  ["Hear your song everywhere you go", "Get a movie made about your love story"],
  ["Be game night rivals", "Be game night teammates"],
  ["Rewatch your favorite show forever", "Always watch something new"],
  ["Your partner cooks every meal", "You cook every meal"],
  ["Ski trip together", "Tropical island together"],
  ["Huge wedding with everyone", "Secret elopement adventure"],
  ["Time travel to your first kiss", "Skip ahead to your 50th anniversary party"],
  ["Share one giant blanket (that gets stolen)", "Two separate blankets forever"],
  ["Be a famous couple", "Be a completely private couple"],
  ["Get serenaded in public", "Get a heartfelt love letter"],
];

// This or That — rapid-fire pairs, compatibility % at the end.
const TOT = [
  ["Coffee", "Tea"],
  ["Sunrise", "Sunset"],
  ["Pizza", "Burgers"],
  ["Dogs", "Cats"],
  ["Beach", "Mountains"],
  ["Summer", "Winter"],
  ["Books", "Movies"],
  ["Sweet", "Salty"],
  ["Early bird", "Night owl"],
  ["Texting", "Calling"],
  ["City", "Countryside"],
  ["Cooking at home", "Eating out"],
  ["Rain", "Snow"],
  ["Rollercoasters", "Ferris wheels"],
  ["Netflix", "YouTube"],
  ["Chocolate", "Vanilla"],
  ["Big breakfast", "Big dinner"],
  ["Camping", "Hotel"],
  ["Singing", "Dancing"],
  ["Board games", "Video games"],
  ["Spicy", "Mild"],
  ["Window seat", "Aisle seat"],
  ["Gold", "Silver"],
  ["Comedy", "Horror"],
  ["Planned", "Spontaneous"],
  ["Saving", "Spending"],
  ["Big party", "Small gathering"],
  ["Pancakes", "Waffles"],
  ["Smoothies", "Milkshakes"],
  ["Ocean", "Pool"],
  ["Concert", "Theatre"],
  ["Bath", "Shower"],
  ["Old music", "New music"],
  ["Driver", "Passenger princess/prince"],
  ["Ice cream cone", "Ice cream cup"],
  ["Morning workout", "Evening workout"],
  ["Fiction", "Non-fiction"],
  ["Stay up late talking", "Fall asleep instantly"],
  ["Surprise gifts", "Wishlist gifts"],
  ["Cheese", "Extra cheese"],
];

// Who Knows Me Better — each round one player is the "subject".
// `you` is shown to the subject, `them` to the guesser ({name} is replaced client-side).
const WKM = [
  { you: "What's your go-to comfort food?", them: "What's {name}'s go-to comfort food?", options: ["Pizza", "Ice cream", "Instant noodles", "Chocolate"] },
  { you: "What's your dream vacation?", them: "What's {name}'s dream vacation?", options: ["Beach resort", "European city tour", "Mountain adventure", "Cozy staycation"] },
  { you: "How do you love spending a free Sunday?", them: "How does {name} love spending a free Sunday?", options: ["Sleeping in", "Out with friends", "Binge-watching shows", "Being outdoors"] },
  { you: "What's your biggest pet peeve?", them: "What's {name}'s biggest pet peeve?", options: ["Slow walkers", "Loud chewing", "People being late", "Phones at dinner"] },
  { you: "What's your secret superpower?", them: "What's {name}'s secret superpower?", options: ["Singing", "Cooking", "Weirdly good at trivia", "Making people laugh"] },
  { you: "How do you most like to receive love?", them: "How does {name} most like to receive love?", options: ["Sweet words", "Quality time", "Little gifts", "Hugs and cuddles"] },
  { you: "What would you grab first in a fire (people & pets are safe)?", them: "What would {name} grab first in a fire (people & pets are safe)?", options: ["Phone", "Photos & keepsakes", "Laptop", "Wallet"] },
  { you: "Which superpower would you choose?", them: "Which superpower would {name} choose?", options: ["Mind reading", "Invisibility", "Flying", "Time travel"] },
  { you: "What's your favorite season?", them: "What's {name}'s favorite season?", options: ["Spring", "Summer", "Autumn", "Winter"] },
  { you: "What's your ideal date night?", them: "What's {name}'s ideal date night?", options: ["Fancy dinner", "Movie marathon at home", "Concert or event", "Long walk & street food"] },
  { you: "What stresses you out the most?", them: "What stresses {name} out the most?", options: ["Work or school", "Money", "Running late", "Social situations"] },
  { you: "What's your karaoke energy?", them: "What's {name}'s karaoke energy?", options: ["Romantic ballad", "2000s throwback", "Full rap verse", "Refuses to sing"] },
  { you: "Pick your dessert!", them: "Which dessert would {name} pick?", options: ["Cheesecake", "Brownie sundae", "Gulab jamun", "Just more fries"] },
  { you: "What's the first thing you do when you wake up?", them: "What's the first thing {name} does when they wake up?", options: ["Check phone", "Hit snooze", "Straight to shower", "Coffee or tea first"] },
  { you: "What's your favorite movie genre?", them: "What's {name}'s favorite movie genre?", options: ["Romance", "Action", "Comedy", "Horror/Thriller"] },
  { you: "You win the lottery — first big purchase?", them: "{name} wins the lottery — first big purchase?", options: ["A house", "Travel the world", "A dream car", "Invest and save it"] },
  { you: "What's your ideal pet?", them: "What's {name}'s ideal pet?", options: ["Dog", "Cat", "Something tiny (bird/fish)", "No pets, thanks"] },
  { you: "What are you most likely to cry at?", them: "What is {name} most likely to cry at?", options: ["Sad movies", "Weddings", "Animal videos", "Nothing, I'm a rock"] },
  { you: "What's your go-to drink order?", them: "What's {name}'s go-to drink order?", options: ["Coffee", "Bubble tea", "Juice or smoothie", "Just water"] },
  { you: "What kind of gift wins your heart?", them: "What kind of gift wins {name}'s heart?", options: ["Something handmade", "Something fancy", "Something practical", "An experience together"] },
  { you: "What's your perfect breakfast?", them: "What's {name}'s perfect breakfast?", options: ["Big cooked breakfast", "Pancakes or waffles", "Just coffee", "Toast or cereal"] },
  { you: "How do you handle a bad day?", them: "How does {name} handle a bad day?", options: ["Talk it out", "Alone time", "Comfort food", "Sleep it off"] },
  { you: "What's your must-have dream house feature?", them: "What's {name}'s must-have dream house feature?", options: ["Home theater", "Huge kitchen", "Garden or balcony", "Game room"] },
  { you: "Which app eats most of your screen time?", them: "Which app eats most of {name}'s screen time?", options: ["Instagram", "YouTube", "Chats/WhatsApp", "Games"] },
];

// Truth or Dare — remote-friendly so it works when you're not together.
const TOD_TRUTHS = [
  "What was your real first impression of me?",
  "What's the most romantic thing you've ever imagined us doing?",
  "What's one thing you've never told anyone — not even me?",
  "What habit of mine do you secretly find adorable?",
  "What's the most jealous you've ever been?",
  "What's one thing you were nervous about when we started dating?",
  "If we could teleport anywhere right now, where would you take me?",
  "What song secretly makes you think of me?",
  "What's the silliest thing you've done to get my attention?",
  "What's one thing you'd love me to do more often?",
  "When did you first realize you liked me?",
  "What's your favorite memory of us so far?",
  "What's the weirdest thought you've had about our future?",
  "What's something I do that always makes you laugh?",
  "What part of my personality surprised you the most?",
  "If you had to describe me in exactly three words, what would they be?",
  "What's the best compliment I've ever given you?",
  "What's one tiny lie you've told me that you can confess right now?",
  "What do you brag about me to your friends?",
  "What's a dream about us you've never said out loud?",
  "Which of my outfits is your favorite?",
  "What's the first thing you notice when you see me?",
  "What would our couple reality show be called?",
  "What's one thing you want us to try together this year?",
];

const TOD_DARES = [
  "Send the last photo in your camera roll. No explanations allowed.",
  "Do your best impression of me until I say stop.",
  "Send a voice note of you singing our song.",
  "Say something sweet in your most dramatic movie-trailer voice.",
  "Show me the oldest photo of yourself on your phone.",
  "Speak in an accent for the next two rounds.",
  "Send a selfie making the weirdest face you can.",
  "Write me a two-line love poem right now.",
  "Dance with no music for 15 seconds.",
  "Let me pick your phone wallpaper for the next week.",
  "Call me by a brand-new pet name for the rest of the day.",
  "Reenact the moment we first met.",
  "Do 10 jumping jacks while listing reasons you like me.",
  "Show me your most-played song this month.",
  "Compliment me non-stop for 30 seconds.",
  "Draw a portrait of me in 30 seconds and show it.",
  "Reveal your phone's weekly screen time. The real number.",
  "Whisper the next thing you say, no matter what it is.",
  "Send me the last meme you saved.",
  "Make up a 15-second song about us on the spot.",
  "Show the most embarrassing item within arm's reach.",
  "Try to lick your elbow. Really try.",
  "Answer one bonus truth of my choosing.",
  "Let me write your next social media status (nothing too evil).",
];

// The classic 36 Questions (Aron et al.), adapted to couple voice.
// Three sets that get progressively deeper.
const Q36 = [
  "Given the choice of anyone in the world, whom would you want as a dinner guest?",
  "Would you like to be famous? In what way?",
  "Before making a phone call, do you ever rehearse what you're going to say? Why?",
  "What would a perfect day look like for you?",
  "When did you last sing to yourself? And to someone else?",
  "If you could live to 90 keeping either the mind or the body of a 30-year-old for the last 60 years, which would you choose?",
  "Do you have a secret hunch about how you will die?",
  "Name three things we seem to have in common.",
  "What in your life do you feel most grateful for?",
  "If you could change anything about the way you were raised, what would it be?",
  "Take four minutes and tell me your life story in as much detail as you can.",
  "If you could wake up tomorrow having gained one quality or ability, what would it be?",
  "If a crystal ball could tell you the truth about yourself, your life, or the future, what would you want to know?",
  "Is there something you've dreamed of doing for a long time? Why haven't you done it?",
  "What's the greatest accomplishment of your life so far?",
  "What do you value most in a friendship?",
  "What is your most treasured memory?",
  "What is your most terrible memory?",
  "If you knew you had one year left, would you change anything about how you're living? Why?",
  "What does friendship mean to you?",
  "What roles do love and affection play in your life?",
  "Take turns sharing something you consider a positive characteristic of each other — five each.",
  "How close and warm is your family? Do you feel your childhood was happier than most people's?",
  "How do you feel about your relationship with your mother?",
  "Make three true statements starting with the word — for example, 'We are both in this room feeling…'",
  "Complete this sentence: 'I wish I had someone with whom I could share…'",
  "If we were about to become much closer, what would be important for me to know about you?",
  "Tell me what you like about me — be more honest than you'd be with someone you just met.",
  "Share an embarrassing moment from your life.",
  "When did you last cry in front of another person? And by yourself?",
  "Tell me something you already like about me.",
  "What, if anything, is too serious to joke about?",
  "If you were to die this evening with no chance to talk to anyone, what would you most regret not having told someone? Why haven't you told them yet?",
  "Your house catches fire — loved ones and pets are safe, and you can save one item. What is it, and why?",
  "Of all the people in your family, whose death would affect you the most? Why?",
  "Share a personal problem and ask my advice. Then ask me how I think you're feeling about it.",
];

// Drawing & Guessing — easy-to-draw single words.
const DRAW_WORDS = [
  "heart", "sun", "moon", "star", "house", "tree", "flower", "cat", "dog",
  "fish", "bird", "car", "bus", "bicycle", "train", "plane", "boat", "pizza",
  "burger", "cake", "apple", "banana", "cup", "coffee", "book", "phone",
  "clock", "key", "door", "window", "chair", "table", "bed", "lamp", "shoe",
  "hat", "shirt", "glasses", "umbrella", "rain", "cloud", "snowman", "beach",
  "mountain", "bridge", "candle", "balloon", "gift", "ring", "crown", "ghost",
  "robot", "rocket", "rainbow", "butterfly", "spider", "snake", "turtle",
  "elephant", "lion", "monkey", "penguin", "guitar", "drum", "camera",
  "ladder", "kite", "cactus", "igloo", "lighthouse",
];

module.exports = { WYR, TOT, WKM, TOD_TRUTHS, TOD_DARES, Q36, DRAW_WORDS };
