// Question banks for all three games.

// Would You Rather — both players pick one of two options, revealed together.
const WYR = [
  ["Travel the world together for a year", "Build your dream home together"],
  ["Always know how your partner feels", "Have them always know how you feel"],
  ["Cozy movie night in", "Fancy night out"],
  ["Beach honeymoon", "Mountain cabin honeymoon"],
  ["Always share one dessert", "Always get your own dessert"],
  ["Relive your first date", "Peek 10 years into your future"],
  ["Take a couples cooking class", "Take a couples dance class"],
  ["Never argue again", "Argue sometimes but always make up sweetly"],
  ["Get matching tattoos", "Wear matching outfits for a year"],
  ["Breakfast in bed every weekend", "A surprise date once a month"],
  ["Road trip with zero plan", "Perfectly planned vacation"],
  ["Double date every week", "Never double date again"],
  ["Sing a karaoke duet in public", "Slow dance in public"],
  ["Your partner picks your outfits for a month", "You pick theirs for a month"],
  ["Live in a big city together", "Live in a tiny town together"],
  ["Adopt five dogs", "Adopt five cats"],
  ["Only text each other all day", "Only call each other"],
  ["Win the lottery but keep it secret", "Small raise you can celebrate loudly"],
  ["Stargazing picnic", "Sunrise hike"],
  ["Swap phones for a day", "Swap chores for a month"],
  ["Hear your song everywhere you go", "Get a movie made about your love story"],
  ["Be game night rivals", "Be game night teammates"],
  ["Rewatch your favorite show forever", "Always watch something new"],
  ["Your partner cooks every meal", "You cook every meal"],
  ["Ski trip together", "Tropical island together"],
  ["Huge wedding with everyone", "Secret elopement adventure"],
  ["Time travel to your first kiss", "Skip ahead to your 50th anniversary party"],
  ["Share one giant blanket (that gets stolen)", "Two separate blankets forever"],
  ["Be a famous couple", "Be a completely private couple"],
  ["Get serenaded in public", "Get a heartfelt love letter"],
];

// This or That — rapid-fire pairs, compatibility % at the end.
const TOT = [
  ["Coffee", "Tea"],
  ["Sunrise", "Sunset"],
  ["Pizza", "Burgers"],
  ["Dogs", "Cats"],
  ["Beach", "Mountains"],
  ["Summer", "Winter"],
  ["Books", "Movies"],
  ["Sweet", "Salty"],
  ["Early bird", "Night owl"],
  ["Texting", "Calling"],
  ["City", "Countryside"],
  ["Cooking at home", "Eating out"],
  ["Rain", "Snow"],
  ["Rollercoasters", "Ferris wheels"],
  ["Netflix", "YouTube"],
  ["Chocolate", "Vanilla"],
  ["Big breakfast", "Big dinner"],
  ["Camping", "Hotel"],
  ["Singing", "Dancing"],
  ["Board games", "Video games"],
  ["Spicy", "Mild"],
  ["Window seat", "Aisle seat"],
  ["Gold", "Silver"],
  ["Comedy", "Horror"],
  ["Planned", "Spontaneous"],
  ["Saving", "Spending"],
  ["Big party", "Small gathering"],
  ["Pancakes", "Waffles"],
  ["Smoothies", "Milkshakes"],
  ["Ocean", "Pool"],
  ["Concert", "Theatre"],
  ["Bath", "Shower"],
  ["Old music", "New music"],
  ["Driver", "Passenger princess/prince"],
  ["Ice cream cone", "Ice cream cup"],
  ["Morning workout", "Evening workout"],
  ["Fiction", "Non-fiction"],
  ["Stay up late talking", "Fall asleep instantly"],
  ["Surprise gifts", "Wishlist gifts"],
  ["Cheese", "Extra cheese"],
];

// Who Knows Me Better — each round one player is the "subject".
// `you` is shown to the subject, `them` to the guesser ({name} is replaced client-side).
const WKM = [
  { you: "What's your go-to comfort food?", them: "What's {name}'s go-to comfort food?", options: ["Pizza", "Ice cream", "Instant noodles", "Chocolate"] },
  { you: "What's your dream vacation?", them: "What's {name}'s dream vacation?", options: ["Beach resort", "European city tour", "Mountain adventure", "Cozy staycation"] },
  { you: "How do you love spending a free Sunday?", them: "How does {name} love spending a free Sunday?", options: ["Sleeping in", "Out with friends", "Binge-watching shows", "Being outdoors"] },
  { you: "What's your biggest pet peeve?", them: "What's {name}'s biggest pet peeve?", options: ["Slow walkers", "Loud chewing", "People being late", "Phones at dinner"] },
  { you: "What's your secret superpower?", them: "What's {name}'s secret superpower?", options: ["Singing", "Cooking", "Weirdly good at trivia", "Making people laugh"] },
  { you: "How do you most like to receive love?", them: "How does {name} most like to receive love?", options: ["Sweet words", "Quality time", "Little gifts", "Hugs and cuddles"] },
  { you: "What would you grab first in a fire (people & pets are safe)?", them: "What would {name} grab first in a fire (people & pets are safe)?", options: ["Phone", "Photos & keepsakes", "Laptop", "Wallet"] },
  { you: "Which superpower would you choose?", them: "Which superpower would {name} choose?", options: ["Mind reading", "Invisibility", "Flying", "Time travel"] },
  { you: "What's your favorite season?", them: "What's {name}'s favorite season?", options: ["Spring", "Summer", "Autumn", "Winter"] },
  { you: "What's your ideal date night?", them: "What's {name}'s ideal date night?", options: ["Fancy dinner", "Movie marathon at home", "Concert or event", "Long walk & street food"] },
  { you: "What stresses you out the most?", them: "What stresses {name} out the most?", options: ["Work or school", "Money", "Running late", "Social situations"] },
  { you: "What's your karaoke energy?", them: "What's {name}'s karaoke energy?", options: ["Romantic ballad", "2000s throwback", "Full rap verse", "Refuses to sing"] },
  { you: "Pick your dessert!", them: "Which dessert would {name} pick?", options: ["Cheesecake", "Brownie sundae", "Gulab jamun", "Just more fries"] },
  { you: "What's the first thing you do when you wake up?", them: "What's the first thing {name} does when they wake up?", options: ["Check phone", "Hit snooze", "Straight to shower", "Coffee or tea first"] },
  { you: "What's your favorite movie genre?", them: "What's {name}'s favorite movie genre?", options: ["Romance", "Action", "Comedy", "Horror/Thriller"] },
  { you: "You win the lottery — first big purchase?", them: "{name} wins the lottery — first big purchase?", options: ["A house", "Travel the world", "A dream car", "Invest and save it"] },
  { you: "What's your ideal pet?", them: "What's {name}'s ideal pet?", options: ["Dog", "Cat", "Something tiny (bird/fish)", "No pets, thanks"] },
  { you: "What are you most likely to cry at?", them: "What is {name} most likely to cry at?", options: ["Sad movies", "Weddings", "Animal videos", "Nothing, I'm a rock"] },
  { you: "What's your go-to drink order?", them: "What's {name}'s go-to drink order?", options: ["Coffee", "Bubble tea", "Juice or smoothie", "Just water"] },
  { you: "What kind of gift wins your heart?", them: "What kind of gift wins {name}'s heart?", options: ["Something handmade", "Something fancy", "Something practical", "An experience together"] },
  { you: "What's your perfect breakfast?", them: "What's {name}'s perfect breakfast?", options: ["Big cooked breakfast", "Pancakes or waffles", "Just coffee", "Toast or cereal"] },
  { you: "How do you handle a bad day?", them: "How does {name} handle a bad day?", options: ["Talk it out", "Alone time", "Comfort food", "Sleep it off"] },
  { you: "What's your must-have dream house feature?", them: "What's {name}'s must-have dream house feature?", options: ["Home theater", "Huge kitchen", "Garden or balcony", "Game room"] },
  { you: "Which app eats most of your screen time?", them: "Which app eats most of {name}'s screen time?", options: ["Instagram", "YouTube", "Chats/WhatsApp", "Games"] },
];

module.exports = { WYR, TOT, WKM };
